// Generated by LiveScript 1.4.0
/**
 * @package    CleverStyle Framework
 * @subpackage System module
 * @category   modules
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2015-2016, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */
(function(){
  var L;
  L = cs.Language('system_admin_storages_');
  Polymer({
    'is': 'cs-system-admin-storages-form',
    behaviors: [cs.Polymer.behaviors.Language('system_admin_storages_')],
    properties: {
      add: Boolean,
      storageIndex: Number,
      storages: Array,
      storage: {
        type: Object,
        value: {
          url: '',
          host: '',
          connection: 'Local',
          user: '',
          password: ''
        }
      },
      engines: Array
    },
    ready: function(){
      var this$ = this;
      cs.api(['get		api/System/admin/storages', 'engines	api/System/admin/storages']).then(function(arg$){
        this$.storages = arg$[0], this$.engines = arg$[1];
        if (!this$.add) {
          this$.storages.forEach(function(storage){
            if (this$.storageIndex == storage.index) {
              this$.set('storage', storage);
            }
          });
        }
      });
    },
    _save: function(){
      var method, suffix;
      method = this.add ? 'post' : 'patch';
      suffix = !this.add ? '/' + this.storageIndex : '';
      cs.api(method + " api/System/admin/storages" + suffix, this.storage).then(function(){
        cs.ui.notify(L.changes_saved, 'success', 5);
      });
    },
    _test_connection: function(e){
      var $modal;
      $modal = cs.ui.simple_modal("<div>\n	<h3 class=\"cs-text-center\">" + L.test_connection + "</h3>\n	<progress is=\"cs-progress\" infinite></progress>\n</div>");
      cs.api('test api/System/admin/storages', this.storage).then(function(){
        modal.querySelector('progress').outerHTML = "<p class=\"cs-text-center cs-block-success cs-text-success\" style=text-transform:capitalize;\">" + L.success + "</p>";
      })['catch'](function(o){
        clearTimeout(o.timeout);
        modal.querySelector('progress').outerHTML = "<p class=\"cs-text-center cs-block-error cs-text-error\" style=text-transform:capitalize;\">" + L.failed + "</p>";
      });
    }
  });
}).call(this);
