// Generated by CoffeeScript 1.4.0

/**
 * @package		Plupload
 * @category	modules
 * @author		Moxiecode Systems AB
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com> (integration into CleverStyle CMS)
 * @copyright	Moxiecode Systems AB
 * @license		GNU GPL v2, see license.txt
*/


/**
 * Files uploading interface
 *
 * @param {object}		button
 * @param {function}	success
 * @param {function}	error
 * @param {function}	progress
 * @param {bool}		multi
 *
 * @return {function}
*/


(function() {

  cs.file_upload = function(button, success, error, progress, multi) {
    var file_element, files, uploader, _ref, _ref1;
    files = [];
    uploader = new plupload.Uploader({
      runtimes: 'html5',
      max_file_size: (_ref = (_ref1 = cs.plupload) != null ? _ref1.max_file_size : void 0) != null ? _ref : null,
      url: '/Plupload',
      multi_selection: multi,
      multipart: true
    });
    uploader.init();
    file_element = $('#' + uploader.id + '_html5');
    if (button) {
      button.click(function() {
        return file_element.click();
      });
    }
    if (!file_element.attr('accept')) {
      file_element.removeAttr('accept');
    }
    uploader.bind('FilesAdded', function() {
      uploader.refresh();
      return uploader.start();
    });
    if (progress) {
      uploader.bind('UploadProgress', function(uploader, file) {
        return progress(file.percent, file.size, file.loaded, file.name);
      });
    }
    if (success) {
      uploader.bind('FileUploaded', function(uploader, files_, res) {
        var response;
        response = $.parseJSON(res.response);
        if (!response.error) {
          return files.push(response.result);
        } else {
          return alert(response.error.message);
        }
      });
      uploader.bind('UploadComplete', function() {
        success(files);
        return files = [];
      });
    }
    if (error) {
      uploader.bind('Error', function(uploader, error) {
        return error(error);
      });
    }
    this.stop = function() {
      return uploader.stop();
    };
    this.destroy = function() {
      return uploader.destroy();
    };
    this.browse = function() {
      return file_element.click();
    };
    return this;
  };

  return;

}).call(this);
