// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer({
    'is': 'cs-nav-button-group',
    'extends': 'nav',
    behaviors: [Polymer.cs.behaviors["this"], Polymer.cs.behaviors.tooltip],
    hostAttributes: {
      role: 'group'
    },
    properties: {
      vertical: {
        reflectToAttribute: true,
        type: Boolean
      }
    }
  });

}).call(this);
