// Generated by CoffeeScript 1.4.0

/**
 * @package   Shop
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  Polymer({
    ready: function() {
      this.$.img.innerHTML = this.querySelector('#img').outerHTML;
      this.href = this.querySelector('#link').href;
      return $(this.querySelector('#nested')).addClass('uk-grid uk-grid-small uk-grid-width-1-4 uk-width-1-1');
    }
  });

}).call(this);
