// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer({
    'is': 'cs-input-text',
    'extends': 'input',
    properties: {
      compact: {
        reflectToAttribute: true,
        type: Boolean
      },
      fullWidth: {
        reflectToAttribute: true,
        type: Boolean
      },
      tight: Boolean
    },
    ready: function() {
      if (this.tight && this.nextSibling.nodeType === Node.TEXT_NODE) {
        this.nextSibling.parentNode.removeChild(this.nextSibling);
      }
      this.addEventListener('change', (function(_this) {
        return function() {
          return _this.fire('value-changed');
        };
      })(this));
      return this.addEventListener('input', (function(_this) {
        return function() {
          return _this.fire('value-changed');
        };
      })(this));
    }
  });

}).call(this);
