// Generated by LiveScript 1.4.0
/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  Polymer({
    'is': 'cs-blogs-admin-sections-list',
    behaviors: [cs.Polymer.behaviors.Language('blogs_')],
    properties: {
      sections: Array
    },
    ready: function(){
      this._reload_sections();
    },
    _reload_sections: function(){
      var this$ = this;
      $.ajax({
        url: 'api/Blogs/admin/sections',
        type: 'get',
        success: function(sections){
          this$.set('sections', sections);
        }
      });
    }
  });
}).call(this);
