// Generated by LiveScript 1.4.0
/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  Polymer({
    'is': 'cs-blogs-admin-sections-list',
    behaviors: [cs.Polymer.behaviors.Language('blogs_')],
    properties: {
      sections: Array
    },
    ready: function(){
      this._reload_sections();
    },
    _reload_sections: function(){
      var this$ = this;
      $.ajax({
        url: 'api/Blogs/admin/sections',
        type: 'get',
        success: function(sections){
          this$.set('sections', sections);
        }
      });
    },
    _add: function(){
      $(cs.ui.simple_modal("<h3>" + this.L.addition_of_posts_section + "</h3>\n<cs-blogs-admin-sections-add-edit-form/>")).on('close', bind$(this, '_reload_sections'));
    },
    _edit: function(e){
      var title;
      title = this.L.editing_of_posts_section(e.model.item.title);
      $(cs.ui.simple_modal("<h2>" + title + "</h2>\n<cs-blogs-admin-sections-add-edit-form id=\"" + e.model.item.id + "\"/>")).on('close', bind$(this, '_reload_sections'));
    },
    _delete: function(e){
      var this$ = this;
      cs.ui.confirm(this.L.sure_to_delete_posts_section(e.model.item.title), function(){
        $.ajax({
          url: 'api/Blogs/admin/sections/' + e.model.item.id,
          type: 'delete',
          success: function(){
            cs.ui.notify(this$.L.changes_saved, 'success', 5);
            this$._reload_sections();
          }
        });
      });
    }
  });
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
}).call(this);
