ALTER TABLE `[prefix]blogs_posts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]blogs_posts_sections` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]blogs_posts_tags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]blogs_sections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]blogs_tags` DROP INDEX `text`, ADD UNIQUE `text` (`text`(191));
ALTER TABLE `[prefix]blogs_tags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]texts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]texts_data` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
REPAIR TABLE `[prefix]blogs_posts`;
OPTIMIZE TABLE `[prefix]blogs_posts`;
REPAIR TABLE `[prefix]blogs_posts_sections`;
OPTIMIZE TABLE `[prefix]blogs_posts_sections`;
REPAIR TABLE `[prefix]blogs_posts_tags`;
OPTIMIZE TABLE `[prefix]blogs_posts_tags`;
REPAIR TABLE `[prefix]blogs_sections`;
OPTIMIZE TABLE `[prefix]blogs_sections`;
REPAIR TABLE `[prefix]blogs_tags`;
OPTIMIZE TABLE `[prefix]blogs_tags`;
REPAIR TABLE `[prefix]texts`;
OPTIMIZE TABLE `[prefix]texts`;
REPAIR TABLE `[prefix]texts_data`;
OPTIMIZE TABLE `[prefix]texts_data`;
