// Generated by CoffeeScript 1.9.3

/**
 * @package    CleverStyle CMS
 * @subpackage System module
 * @category   modules
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2015, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */

(function() {
  var L;

  L = cs.Language;

  Polymer({
    tooltip_animation: '{animation:true,delay:200}',
    L: L,
    permissions: [],
    created: function() {
      return this.permissions = JSON.parse(this.querySelector('script').innerHTML);
    },
    domReady: function() {
      return $(this.shadowRoot).cs().tooltips_inside();
    }
  });

}).call(this);
