// Generated by CoffeeScript 1.9.3

/**
 * @package   Shop
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer({
    'is': 'cs-shop-category-nested',
    'extends': 'article',
    properties: {
      href: String,
      category_title: String
    },
    ready: function() {
      var link;
      $(this.$.img).prepend(this.querySelector('#img').outerHTML);
      link = this.querySelector('#link');
      this.set('href', link.href);
      return this.set('category_title', link.textContent);
    }
  });

}).call(this);
