CREATE TABLE "[prefix]config" (
    "domain" text NOT NULL,
    "core" text NOT NULL,
    "db" text NOT NULL,
    "storage" text NOT NULL,
    "components" text NOT NULL
);

COMMENT ON TABLE "[prefix]config" IS 'Settings';

CREATE TABLE "[prefix]groups" (
    "id" smallserial,
    "title" text NOT NULL,
    "description" text NOT NULL
);

COMMENT ON COLUMN "[prefix]groups"."id" IS 'WARNING: Never delete first 2 groups!';

CREATE TABLE "[prefix]groups_permissions" (
    "id" smallint NOT NULL,
    "permission" smallint NOT NULL,
    "value" smallint NOT NULL
);

COMMENT ON COLUMN "[prefix]groups_permissions"."id" IS 'Group id';
COMMENT ON COLUMN "[prefix]groups_permissions"."permission" IS 'Permission id';

CREATE TABLE "[prefix]keys" (
    "id" bigserial,
    "key" bytea NOT NULL,
    "expire" numeric DEFAULT '0'::numeric NOT NULL,
    "data" text NOT NULL
);

COMMENT ON TABLE "[prefix]keys" IS 'Temporary keys';

COMMENT ON COLUMN "[prefix]keys"."key" IS 'Key may be generated by sha224 algorithm';

CREATE TABLE "[prefix]permissions" (
    "id" smallserial,
    "label" text NOT NULL,
    "group" text NOT NULL
);

CREATE TABLE "[prefix]sessions" (
    "id" text NOT NULL,
    "user" bigint NOT NULL,
    "created" numeric NOT NULL,
    "expire" numeric NOT NULL,
    "user_agent" text NOT NULL,
    "remote_addr" text NOT NULL,
    "ip" text NOT NULL,
    "data" text NOT NULL
);

COMMENT ON COLUMN "[prefix]sessions"."user" IS 'User id';
COMMENT ON COLUMN "[prefix]sessions"."remote_addr" IS 'hex value, obtained by function ip2hex()';
COMMENT ON COLUMN "[prefix]sessions"."ip" IS 'hex value, obtained by function ip2hex()';

CREATE TABLE "[prefix]texts" (
    "id" bigserial,
    "label" text NOT NULL,
    "group" text NOT NULL
);

CREATE TABLE "[prefix]texts_data" (
    "id" numeric NOT NULL,
    "id_" text NOT NULL,
    "lang" text NOT NULL,
    "text" text NOT NULL,
    "text_md5" text NOT NULL
);

COMMENT ON COLUMN "[prefix]texts_data"."id" IS 'id from texts table';

CREATE TABLE "[prefix]users" (
    "id" bigserial,
    "login" text NOT NULL,
    "login_hash" text NOT NULL,
    "username" text DEFAULT ''::text NOT NULL,
    "password_hash" text DEFAULT ''::text NOT NULL,
    "email" text DEFAULT ''::text NOT NULL,
    "email_hash" text DEFAULT ''::text NOT NULL,
    "language" text DEFAULT ''::text NOT NULL,
    "timezone" text DEFAULT ''::text NOT NULL,
    "reg_date" numeric DEFAULT '0'::numeric NOT NULL,
    "reg_ip" text NOT NULL DEFAULT ''::text,
    "reg_key" text DEFAULT ''::text NOT NULL,
    "status" smallint DEFAULT '-1'::numeric NOT NULL,
    "avatar" text DEFAULT ''::text NOT NULL
);

COMMENT ON COLUMN "[prefix]users"."id" IS 'WARNING: Never delete first 2 users!';
COMMENT ON COLUMN "[prefix]users"."login_hash" IS 'hash method - sha224';
COMMENT ON COLUMN "[prefix]users"."email_hash" IS 'hash method - sha224';
COMMENT ON COLUMN "[prefix]users"."reg_ip" IS 'hex value, obtained by function ip2hex()';
COMMENT ON COLUMN "[prefix]users"."status" IS '''-1'' - not activated (for example after registration), 0 - inactive, 1 - active';

CREATE TABLE "[prefix]users_data" (
    "id" bigint NOT NULL,
    "item" text NOT NULL,
    "value" text NOT NULL
);

COMMENT ON COLUMN "[prefix]users_data"."id" IS 'User id';

CREATE TABLE "[prefix]users_groups" (
    "id" bigint NOT NULL,
    "group" smallint NOT NULL,
    "priority" smallint NOT NULL
);

COMMENT ON COLUMN "[prefix]users_groups"."id" IS 'User id';
COMMENT ON COLUMN "[prefix]users_groups"."group" IS 'Group id';
COMMENT ON COLUMN "[prefix]users_groups"."priority" IS 'Lower priority is more important';

CREATE TABLE "[prefix]users_permissions" (
    "id" bigint NOT NULL,
    "permission" smallint NOT NULL,
    "value" smallint NOT NULL
);

COMMENT ON COLUMN "[prefix]users_permissions"."id" IS 'User id';
COMMENT ON COLUMN "[prefix]users_permissions"."permission" IS 'Permission id';

INSERT INTO "[prefix]groups" ("title", "description") VALUES ('Administrators', 'Administrators'), ('Users', 'Users');

INSERT INTO "[prefix]permissions" ("label", "group") VALUES ('index', 'admin/System'), ('index', 'api/System');

INSERT INTO "[prefix]users" ("login", "login_hash", "status") VALUES ('guest', '5cf371cef0648f2656ddc13b773aa642251267dbd150597506e96c3a', '1');

INSERT INTO "[prefix]users_groups" ("id", "group", "priority") VALUES (2, 1, 0), (2, 2, 1);

ALTER TABLE ONLY "[prefix]config" ADD CONSTRAINT "[prefix]config_primary" PRIMARY KEY ("domain");

ALTER TABLE ONLY "[prefix]groups" ADD CONSTRAINT "[prefix]groups_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]groups_permissions" ADD CONSTRAINT "[prefix]groups_permissions_primary" PRIMARY KEY ("id", "permission");

ALTER TABLE ONLY "[prefix]keys" ADD CONSTRAINT "[prefix]keys_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]permissions" ADD CONSTRAINT "[prefix]permissions_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]sessions" ADD CONSTRAINT "[prefix]sessions_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]texts" ADD CONSTRAINT "[prefix]texts_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]texts_data" ADD CONSTRAINT "[prefix]texts_data_primary" PRIMARY KEY ("id", "lang");

ALTER TABLE ONLY "[prefix]users" ADD CONSTRAINT "[prefix]users_primary" PRIMARY KEY ("id");

ALTER TABLE ONLY "[prefix]users_data" ADD CONSTRAINT "[prefix]users_data_primary" PRIMARY KEY ("id", "item");

ALTER TABLE ONLY "[prefix]users_groups" ADD CONSTRAINT "[prefix]users_groups_primary" PRIMARY KEY ("id", "group");

ALTER TABLE ONLY "[prefix]users_permissions" ADD CONSTRAINT "[prefix]users_permissions_primary" PRIMARY KEY ("id", "permission");

CREATE INDEX "[prefix]keys_expire" ON "[prefix]keys" USING btree ("expire");
CREATE INDEX "[prefix]keys_key" ON "[prefix]keys" USING btree ("key");

CREATE INDEX "[prefix]permissions_group" ON "[prefix]permissions" USING btree ("group");
CREATE INDEX "[prefix]permissions_label" ON "[prefix]permissions" USING btree ("label");

CREATE INDEX "[prefix]sessions_expire" ON "[prefix]sessions" USING btree ("expire");
CREATE INDEX "[prefix]sessions_user" ON "[prefix]sessions" USING btree ("user");

CREATE INDEX "[prefix]texts_label" ON "[prefix]texts" USING btree ("label", "group");

CREATE INDEX "[prefix]texts_data_id_" ON "[prefix]texts_data" USING btree ("id_");
CREATE INDEX "[prefix]texts_data_text_md5" ON "[prefix]texts_data" USING btree ("text_md5");

CREATE INDEX "[prefix]users_email_hash" ON "[prefix]users" USING btree ("email_hash");
CREATE INDEX "[prefix]users_language" ON "[prefix]users" USING btree ("language");
CREATE INDEX "[prefix]users_login" ON "[prefix]users" USING btree ("login", "username", "email");
CREATE INDEX "[prefix]users_login_hash" ON "[prefix]users" USING btree ("login_hash");
CREATE INDEX "[prefix]users_status" ON "[prefix]users" USING btree ("status");

CREATE INDEX "[prefix]users_data_item" ON "[prefix]users_data" USING btree ("item");

CREATE INDEX "[prefix]users_groups_group" ON "[prefix]users_groups" USING btree ("group");
CREATE INDEX "[prefix]users_groups_priority" ON "[prefix]users_groups" USING btree ("priority");
