// Generated by LiveScript 1.4.0
/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015-2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  var ref$;
  ((ref$ = Polymer.cs || (Polymer.cs = {})).behaviors || (ref$.behaviors = {})).button = {
    properties: {
      action: {
        type: String,
        value: 'button_action'
      },
      active: {
        notify: true,
        reflectToAttribute: true,
        type: Boolean
      },
      bind: Object,
      empty: {
        reflectToAttribute: true,
        type: Boolean
      },
      forceFullsize: {
        reflectToAttribute: true,
        type: Boolean
      },
      icon: {
        reflectToAttribute: true,
        type: String
      },
      iconAfter: {
        reflectToAttribute: true,
        type: String
      },
      primary: {
        reflectToAttribute: true,
        type: Boolean
      }
    },
    listeners: {
      tap: '_tap'
    },
    attached: function(){
      this.empty = !this.childNodes.length;
    },
    _tap: function(){
      if (this.bind && this.action) {
        return this.bind[this.action]();
      }
    }
  };
}).call(this);
