// Generated by LiveScript 1.4.0
/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015-2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  var ref$;
  ((ref$ = Polymer.cs || (Polymer.cs = {})).behaviors || (ref$.behaviors = {})).tight = {
    properties: {
      tight: Boolean
    },
    ready: function(){
      if (this.tight && this.nextSibling.nodeType === Node.TEXT_NODE) {
        this.nextSibling.parentNode.removeChild(this.nextSibling);
      }
    }
  };
}).call(this);
