// Generated by LiveScript 1.4.0
/**
 * @package    CleverStyle CMS
 * @subpackage CleverStyle theme
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2015, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */
(function(){
  var L;
  L = cs.Language;
  Polymer({
    'is': 'cs-cleverstyle-header-user-block',
    behaviors: [cs.Polymer.behaviors.Language],
    properties: {
      avatar: '',
      guest: Boolean,
      username: '' + L.guest,
      login: String
    },
    ready: function(){
      this.guest = !!cs.is_guest;
    },
    _sign_in: function(){
      cs.ui.simple_modal("<cs-cleverstyle-sign-in-form/>");
    },
    _registration: function(){
      cs.ui.simple_modal("<cs-cleverstyle-registration-form/>");
    },
    _sign_out: cs.sign_out
  });
}).call(this);
