ALTER TABLE `[prefix]shop_attributes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_categories_attributes` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_items` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_items_attributes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_items_images` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_items_tags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_items_videos` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_orders` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_orders_history` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_orders_items` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_order_statuses` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_shipping_types` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]shop_tags` DROP INDEX `text`, ADD UNIQUE `text` (`text`(191));
ALTER TABLE `[prefix]shop_tags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]texts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]texts_data` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
REPAIR TABLE `[prefix]shop_attributes`;
OPTIMIZE TABLE `[prefix]shop_attributes`;
REPAIR TABLE `[prefix]shop_categories`;
OPTIMIZE TABLE `[prefix]shop_categories`;
REPAIR TABLE `[prefix]shop_categories_attributes`;
OPTIMIZE TABLE `[prefix]shop_categories_attributes`;
REPAIR TABLE `[prefix]shop_items`;
OPTIMIZE TABLE `[prefix]shop_items`;
REPAIR TABLE `[prefix]shop_items_attributes`;
OPTIMIZE TABLE `[prefix]shop_items_attributes`;
REPAIR TABLE `[prefix]shop_items_images`;
OPTIMIZE TABLE `[prefix]shop_items_images`;
REPAIR TABLE `[prefix]shop_items_tags`;
OPTIMIZE TABLE `[prefix]shop_items_tags`;
REPAIR TABLE `[prefix]shop_items_videos`;
OPTIMIZE TABLE `[prefix]shop_items_videos`;
REPAIR TABLE `[prefix]shop_orders`;
OPTIMIZE TABLE `[prefix]shop_orders`;
REPAIR TABLE `[prefix]shop_orders_history`;
OPTIMIZE TABLE `[prefix]shop_orders_history`;
REPAIR TABLE `[prefix]shop_orders_items`;
OPTIMIZE TABLE `[prefix]shop_orders_items`;
REPAIR TABLE `[prefix]shop_order_statuses`;
OPTIMIZE TABLE `[prefix]shop_order_statuses`;
REPAIR TABLE `[prefix]shop_shipping_types`;
OPTIMIZE TABLE `[prefix]shop_shipping_types`;
REPAIR TABLE `[prefix]shop_tags`;
OPTIMIZE TABLE `[prefix]shop_tags`;
REPAIR TABLE `[prefix]shop_tags`;
OPTIMIZE TABLE `[prefix]shop_tags`;
REPAIR TABLE `[prefix]texts`;
OPTIMIZE TABLE `[prefix]texts`;
REPAIR TABLE `[prefix]texts_data`;
OPTIMIZE TABLE `[prefix]texts_data`;
