// Generated by LiveScript 1.4.0
/**
 * @package   Disqus
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2013-2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  window.DISQUSWIDGETS = {
    displayCount: function(data){
      this[data.counts[0].id] = data.counts[0].comments;
    }
  };
}).call(this);
