// Generated by CoffeeScript 1.4.0

/**
 * @package		CleverStyle CMS
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


/*
 # Load configuration from special template elements
*/


(function() {

  [].forEach.call(document.head.querySelectorAll('.cs-config'), function(config) {
    var destination, last_part, target;
    target = config.getAttribute('target').split('.');
    destination = window;
    last_part = null;
    target.forEach(function(target_part) {
      if (target_part !== 'window' && last_part) {
        if (!destination[last_part]) {
          destination[last_part] = {};
        }
        destination = destination[last_part];
      }
      return last_part = target_part;
    });
    return destination[last_part] = JSON.parse(config.innerHTML.substring(4, config.innerHTML.length - 3).replace('-  ', '-', 'g'));
  });

}).call(this);
