// Generated by CoffeeScript 1.9.3

/**
 * @package		CleverStyle CMS
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
 */


/*
  * Load configuration from special template elements
 */

(function() {
  var L, key, translation,
    hasProp = {}.hasOwnProperty;

  [].forEach.call(document.head.querySelectorAll('.cs-config'), function(config) {
    var data, destination, target;
    target = config.getAttribute('target').split('.');
    data = JSON.parse(config.innerHTML);
    destination = window;
    target.forEach(function(target_part, i) {
      var index, value;
      if (target_part !== 'window') {
        if (!destination[target_part]) {
          destination[target_part] = {};
        }
        if (i < target.length - 1) {
          destination = destination[target_part];
        } else {
          if (data instanceof Object && !(data instanceof Array)) {
            destination = destination[target_part];
            for (index in data) {
              value = data[index];
              destination[index] = value;
            }
          } else {
            destination[target_part] = data;
          }
        }
      }
    });
  });

  L = cs.Language;

  for (key in L) {
    if (!hasProp.call(L, key)) continue;
    translation = L[key];
    L[key] = (function(translation) {
      var result;
      result = function() {
        return vsprintf(translation, Array.prototype.slice.call(arguments));
      };
      result.toString = function() {
        return translation;
      };
      return result;
    })(translation);
  }

  L.get = function(key) {
    return L[key].toString();
  };

  L.format = function(key) {
    return vsprintf(L[key].toString(), Array.prototype.slice.call(arguments, 1));
  };

}).call(this);
