// Generated by CoffeeScript 1.4.0

/**
 * @package		CleverStyle CMS
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2011-2014, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {
  var __hasProp = {}.hasOwnProperty;

  $(function() {
    var L;
    L = cs.Language;
    cs.async_call([
      function() {
        window.session_id = cs.getcookie('session');
        return $.ajaxSetup({
          type: 'post',
          data: {
            session: session_id
          },
          error: function(xhr) {
            if (xhr.responseText) {
              return alert(JSON.parse(xhr.responseText).error_description);
            } else {
              return alert(L.connection_error);
            }
          }
        });
      }, function() {
        var key, translation;
        for (key in L) {
          if (!__hasProp.call(L, key)) continue;
          translation = L[key];
          L[key] = (function(translation) {
            var result;
            result = function() {
              return vsprintf(translation, Array.prototype.slice.call(arguments));
            };
            result.toString = function() {
              return translation;
            };
            return result;
          })(translation);
        }
        L.get = function(key) {
          return L[key].toString();
        };
        L.format = function(key) {
          return L[key](arguments[1]);
        };
      }, function() {
        return $('form:not(.cs-no-ui)').addClass('uk-form');
      }, function() {
        return $('input:radio:not(.cs-no-ui)').cs().radio();
      }, function() {
        return $('input:checkbox:not(.cs-no-ui)').cs().checkbox();
      }, function() {
        return $('.cs-table').addClass('uk-table uk-table-condensed uk-table-hover');
      }, function() {
        return $(':button:not(.cs-no-ui), .cs-button, .cs-button-compact').addClass('uk-button').disableSelection();
      }, function() {
        return $('textarea:not(.cs-no-ui)').not('.cs-no-resize, .EDITOR, .SIMPLE_EDITOR').autosize({
          append: "\n"
        });
      }, function() {
        return $('.SIMPLEST_INLINE_EDITOR').prop('contenteditable', true);
      }, function() {
        return $('[data-title]').cs().tooltip();
      }, function() {
        return $('.cs-tabs').cs().tabs();
      }, function() {
        $('.cs-header-sign-in-slide').click(function() {
          $('.cs-header-guest-form').hide('medium');
          $('.cs-header-sign-in-form').show('medium');
          return $('.cs-header-sign-in-email').focus();
        });
        $('.cs-header-registration-slide').click(function() {
          $('.cs-header-guest-form').hide('medium');
          $('.cs-header-registration-form').show('medium');
          return $('.cs-header-registration-email').focus();
        });
        $('.cs-header-restore-password-slide').click(function() {
          $('.cs-header-sign-in-form, .cs-header-registration-form').hide('medium');
          $('.cs-header-restore-password-form').show('medium');
          return $('.cs-header-restore-password-email').focus();
        });
        $('.cs-header-registration-email').keyup(function(event) {
          if (event.which === 13) {
            return $('.cs-header-registration-process').click();
          }
        });
        $('.cs-header-sign-in-form').submit(function() {
          cs.sign_in($('.cs-header-sign-in-email').val(), $('.cs-header-user-password').val());
          return false;
        });
        $('.cs-header-sign-out-process').click(function() {
          return cs.sign_out();
        });
        $('.cs-show-password').click(function() {
          var $this, pass_input;
          $this = $(this);
          pass_input = $this.parent().next().children('input');
          if (pass_input.prop('type') === 'password') {
            pass_input.prop('type', 'text');
            return $this.addClass('uk-icon-unlock-alt').removeClass('uk-icon-lock');
          } else {
            pass_input.prop('type', 'password');
            return $this.addClass('uk-icon-lock').removeClass('uk-icon-unlock-alt');
          }
        });
        $('#current_password').click(function() {
          var $this, password;
          $this = $(this);
          password = $('.cs-profile-current-password');
          if (password.prop('type') === 'password') {
            password.prop('type', 'text');
            return $this.addClass('uk-icon-unlock-alt').removeClass('uk-icon-lock');
          } else {
            password.prop('type', 'password');
            return $this.addClass('uk-icon-lock').removeClass('uk-icon-unlock-alt');
          }
        });
        $('#new_password').click(function() {
          var $this, password;
          $this = $(this);
          password = $('.cs-profile-new-password');
          if (password.prop('type') === 'password') {
            password.prop('type', 'text');
            return $this.addClass('uk-icon-unlock-alt').removeClass('uk-icon-lock');
          } else {
            password.prop('type', 'password');
            return $this.addClass('uk-icon-lock').removeClass('uk-icon-unlock-alt');
          }
        });
        $('.cs-header-registration-process').click(function() {
          var modal;
          if (!cs.rules_text) {
            cs.registration($('.cs-header-registration-email').val());
            return;
          }
          modal = $("<div title=\"" + L.rules_agree + "\">\n	<div>\n		" + cs.rules_text + "\n		<p class=\"cs-right\">\n			<button class=\"cs-registration-continue uk-button uk-button-primary\">" + L.yes + "</button>\n		</p>\n	</div>\n</div>").appendTo('body').cs().modal('show').on('uk.modal.hide', function() {
            return $(this).remove();
          });
          return modal.find('.cs-registration-continue').click(function() {
            modal.cs().modal('close').remove();
            return cs.registration($('.cs-header-registration-email').val());
          });
        });
        $('.cs-header-restore-password-process').click(function() {
          return cs.restore_password($('.cs-header-restore-password-email').val());
        });
        $('.cs-profile-change-password').click(function() {
          return cs.change_password($('.cs-profile-current-password').val(), $('.cs-profile-new-password').val());
        });
        return $('.cs-header-back').click(function() {
          $('.cs-header-guest-form').show('medium');
          return $('.cs-header-registration-form, .cs-header-sign-in-form, .cs-header-restore-password-form').hide('medium');
        });
      }
    ]);
  });

}).call(this);
