/*
 alameda 1.0.0 Copyright jQuery Foundation and other contributors.
 Released under MIT license, http://github.com/requirejs/alameda/LICENSE
*/
var requirejs,require,define;
(function(W,L,A){function la(k,l,f,n){return n||""}function l(k,l){return M.call(k,l)}function f(k,v){return k&&l(k,v)&&k[v]}function D(k,v){for(var f in k)if(l(k,f)&&v(k[f],f))break}function X(k,f,n,q){f&&D(f,function(f,v){if(n||!l(k,v))!q||"object"!==typeof f||!f||Array.isArray(f)||"function"===typeof f||f instanceof RegExp?k[v]=f:(k[v]||(k[v]={}),X(k[v],f,n,q))});return k}function ma(f){if(!f)return f;var l=W;f.split(".").forEach(function(f){l=l[f]});return l}function Y(k){function n(a,b,c){var e,
g,d,h,B,l,k,r;b=b&&b.split("/");var p=m.map,q=p&&p["*"];if(a){a=a.split("/");g=a.length-1;m.nodeIdCompat&&I.test(a[g])&&(a[g]=a[g].replace(I,""));"."===a[0].charAt(0)&&b&&(g=b.slice(0,b.length-1),a=g.concat(a));g=a;B=g.length;for(d=0;d<B;d++)h=g[d],"."===h?(g.splice(d,1),--d):".."===h&&0!==d&&(1!==d||".."!==g[2])&&".."!==g[d-1]&&0<d&&(g.splice(d-1,2),d-=2);a=a.join("/")}if(c&&p&&(b||q)){g=a.split("/");d=g.length;a:for(;0<d;--d){B=g.slice(0,d).join("/");if(b)for(h=b.length;0<h;--h)if(c=f(p,b.slice(0,
h).join("/")))if(c=f(c,B)){e=c;l=d;break a}!k&&q&&f(q,B)&&(k=f(q,B),r=d)}!e&&k&&(e=k,l=r);e&&(g.splice(0,l,e),a=g.join("/"))}return(e=f(m.pkgs,a))?e:a}function q(a){return function(){var b;a.init&&(b=a.init.apply(W,arguments));return b||a.exports&&ma(a.exports)}}function p(a){var b,c,e;for(b=0;b<E.length;b+=1){if("string"!==typeof E[b][0])if(a)E[b].unshift(a),a=A;else break;e=E.shift();c=e[0];--b;l(r,c)||l(C,c)||(l(w,c)?F.apply(A,e):C[c]=e)}a&&(b=f(m.shim,a)||{},F(a,b.deps||[],b.exportsFn))}function N(a,
b){var c=function(e,g,d,h){var f;b&&p();if("string"===typeof e){if(y[e])return y[e](a);h=u(e,a,!0).id;if(!l(r,h))throw Error("Not loaded: "+h);return r[h]}if(e&&!Array.isArray(e)&&(f=e,e=A,Array.isArray(g)&&(e=g,g=d,d=h),b))return c.config(f)(e,g,d);g=g||function(){return Z.call(arguments,0)};return na.then(function(){p();return F(A,e||[],g,d,a)})};c.isBrowser="undefined"!==typeof document&&"undefined"!==typeof navigator;c.nameToUrl=function(a,b,d){var h,l,k,n;(h=f(m.pkgs,a))&&(a=h);if(h=f(P,a))return c.nameToUrl(h,
b,d);if(oa.test(a))h=a+(b||"");else{h=m.paths;l=a.split("/");for(k=l.length;0<k;--k)if(n=l.slice(0,k).join("/"),n=f(h,n)){Array.isArray(n)&&(n=n[0]);l.splice(0,k,n);break}h=l.join("/");h+=b||(/^data\:|^blob\:|\?/.test(h)||d?"":".js");h=("/"===h.charAt(0)||h.match(/^[\w\+\.\-]+:/)?"":m.baseUrl)+h}return m.urlArgs&&!/^blob\:/.test(h)?h+m.urlArgs(a,h):h};c.toUrl=function(b){var g,d=b.lastIndexOf("."),h=b.split("/")[0];-1!==d&&("."!==h&&".."!==h||1<d)&&(g=b.substring(d,b.length),b=b.substring(0,d));return c.nameToUrl(n(b,
a),g,!0)};c.defined=function(b){return l(r,u(b,a,!0).id)};c.specified=function(b){b=u(b,a,!0).id;return l(r,b)||l(w,b)};return c}function O(a,b,c){if(a&&(r[a]=c,requirejs.onResourceLoad))requirejs.onResourceLoad(Q,b.map,b.deps);b.finished=!0;b.resolve(c)}function R(a,b){a.finished=!0;a.rejected=!0;a.reject(b)}function M(a){return function(b){return n(b,a,!0)}}function aa(a){a.factoryCalled=!0;var b,c=a.map.id;try{b=a.factory.apply(r[c],a.values)}catch(e){return R(a,e)}c?b===A&&(a.cjsModule?b=a.cjsModule.exports:
a.usingExports&&(b=r[c])):z.splice(z.indexOf(a),1);O(c,a,b)}function pa(a,b){this.rejected||this.depDefined[b]||(this.depDefined[b]=!0,this.depCount+=1,this.values[b]=a,this.depending||this.depCount!==this.depMax||aa(this))}function ba(a){var b={};b.promise=new L(function(c,e){b.resolve=c;b.reject=function(c){a||z.splice(z.indexOf(b),1);e(c)}});b.map=a?u(a,null,!0):{};b.depCount=0;b.depMax=0;b.values=[];b.depDefined=[];b.depFinished=pa;b.map.pr&&(b.deps=[u(b.map.pr)]);return b}function x(a){var b;
a?(b=l(w,a)&&w[a])||(b=w[a]=ba(a)):(b=ba(),z.push(b));return b}function ca(a,b){return function(c){a.rejected||(c.dynaId||(c.dynaId="id"+(qa+=1),c.requireModules=[b]),R(a,c))}}function da(a,b,c,e){c.depMax+=1;S(a,b).then(function(a){c.depFinished(a,e)},ca(c,a.id))["catch"](ca(c,c.map.id))}function ra(a){function b(b){c||O(a,x(a),b)}var c;b.error=function(b){x(a).reject(b)};b.fromText=function(b,g){var d=x(a),h=u(u(a).n),f=h.id;c=!0;d.factory=function(a,b){return b};g&&(b=g);l(m.config,a)&&(m.config[f]=
m.config[a]);try{t.exec(b)}catch(k){R(d,Error("fromText eval for "+f+" failed: "+k))}p(f);d.deps=[h];da(h,null,d,d.deps.length)};return b}function ea(a,b,c){a.load(b.n,N(c),ra(b.id),m)}function fa(a){var b,c=a?a.indexOf("!"):-1;-1<c&&(b=a.substring(0,c),a=a.substring(c+1,a.length));return[b,a]}function T(a,b,c){var e=a.map.id;b[e]=!0;!a.finished&&a.deps&&a.deps.forEach(function(g){var d=g.id;g=!l(y,d)&&x(d);!g||g.finished||c[d]||(l(b,d)?a.deps.forEach(function(b,c){b.id===d&&a.depFinished(r[d],c)}):
T(g,b,c))});c[e]=!0}function ga(a){var b=[],c=1E3*m.waitSeconds,c=c&&ha+c<(new Date).getTime();0===G&&(a?a.finished||T(a,{},{}):z.length&&z.forEach(function(a){T(a,{},{})}));c?(D(w,function(a){a.finished||b.push(a.map.id)}),a=Error("Timeout for modules: "+b),a.requireModules=b,t.onError(a)):!G&&!z.length||U||(U=!0,setTimeout(function(){U=!1;ga()},70))}function sa(a){setTimeout(function(){a.dynaId&&ia[a.dynaId]||(ia[a.dynaId]=!0,t.onError(a))});return a}var t,F,u,S,y,U,H,Q,r={},C={},m={waitSeconds:7,
baseUrl:"./",paths:{},bundles:{},pkgs:{},shim:{},config:{}},J={},z=[],w={},ja={},ka={},G=0,ha=(new Date).getTime(),qa=0,ia={},K={},P={},na=L.resolve();H="function"===typeof importScripts?function(a){var b=a.url;K[b]||(K[b]=!0,x(a.id),importScripts(b),p(a.id))}:function(a){var b,c=a.id;a=a.url;K[a]||(K[a]=!0,b=document.createElement("script"),b.setAttribute("data-requiremodule",c),b.type=m.scriptType||"text/javascript",b.charset="utf-8",b.async=!0,G+=1,b.addEventListener("load",function(){--G;p(c)},
!1),b.addEventListener("error",function(){--G;var a;a=f(m.paths,c);var g=f(w,c);a&&Array.isArray(a)&&1<a.length?(b.parentNode.removeChild(b),a.shift(),g.map=u(c),H(g.map)):(a=Error("Load failed: "+c+": "+b.src),a.requireModules=[c],x(c).reject(a))},!1),b.src=a,document.head.appendChild(b))};S=function(a,b){var c,e=a.id;c=m.shim[e];if(l(C,e))c=C[e],delete C[e],F.apply(A,c);else if(!l(w,e))if(a.pr)if(c=f(P,e))a.url=t.nameToUrl(c),H(a);else return S(u(a.pr)).then(function(a){var c=u(e,b,!0),h=c.id,k=
f(m.shim,h);l(ka,h)||(ka[h]=!0,k&&k.deps?t(k.deps,function(){ea(a,c,b)}):ea(a,c,b));return x(h).promise});else c&&c.deps?t(c.deps,function(){H(a)}):H(a);return x(e).promise};u=function(a,b,c){if("string"!==typeof a)return a;var e,g,d,h=a+" & "+(b||"")+" & "+!!c;a=fa(a);d=a[0];a=a[1];if(!d&&l(J,h))return J[h];d&&(d=n(d,b,c),e=l(r,d)&&r[d]);d?a=e&&e.normalize?e.normalize(a,M(b)):-1===a.indexOf("!")?n(a,b,c):a:(a=n(a,b,c),a=fa(a),d=a[0],a=a[1],g=t.nameToUrl(a));b={id:d?d+"!"+a:a,n:a,pr:d,url:g};d||(J[h]=
b);return b};y={require:function(a){return N(a)},exports:function(a){var b=r[a];return"undefined"!==typeof b?b:r[a]={}},module:function(a){return{id:a,uri:"",exports:y.exports(a),config:function(){return f(m.config,a)||{}}}}};F=function(a,b,c,e,g){if(!a||!l(ja,a)){ja[a]=!0;var d=x(a);b&&!Array.isArray(b)&&(c=b,b=[]);e||(l(m,"defaultErrback")?m.defaultErrback&&(e=m.defaultErrback):e=sa);e&&d.promise["catch"](e);g=g||a;"function"===typeof c?(!b.length&&c.length&&(c.toString().replace(ta,la).replace(ua,
function(a,c){b.push(c)}),b=(1===c.length?["require"]:["require","exports","module"]).concat(b)),d.factory=c,d.deps=b,d.depending=!0,b.forEach(function(c,e){var f;b[e]=f=u(c,g,!0);c=f.id;"require"===c?d.values[e]=y.require(a):"exports"===c?(d.values[e]=y.exports(a),d.usingExports=!0):"module"===c?d.values[e]=d.cjsModule=y.module(a):void 0===c?d.values[e]=void 0:da(f,g,d,e)}),d.depending=!1,d.depCount===d.depMax&&aa(d)):a&&O(a,d,c);ha=(new Date).getTime();a||ga(d);return d.promise}};t=N(null,!0);t.config=
function(a){if(a.context&&a.context!==k)return Y(a.context).config(a);J={};a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");if("string"===typeof a.urlArgs){var b=a.urlArgs;a.urlArgs=function(a,c){return(-1===c.indexOf("?")?"?":"&")+b}}var c=m.shim,e={paths:!0,bundles:!0,config:!0,map:!0};D(a,function(a,b){e[b]?(m[b]||(m[b]={}),X(m[b],a,!0,!0)):m[b]=a});a.bundles&&D(a.bundles,function(a,b){a.forEach(function(a){a!==b&&(P[a]=b)})});a.shim&&(D(a.shim,function(a,b){Array.isArray(a)&&
(a={deps:a});!a.exports&&!a.init||a.exportsFn||(a.exportsFn=q(a));c[b]=a}),m.shim=c);a.packages&&a.packages.forEach(function(a){var b;a="string"===typeof a?{name:a}:a;b=a.name;a.location&&(m.paths[b]=a.location);m.pkgs[b]=a.name+"/"+(a.main||"main").replace(va,"").replace(I,"")});(a.deps||a.callback)&&t(a.deps,a.callback);return t};t.onError=function(a){throw a;};Q={id:k,defined:r,waiting:C,config:m,deferreds:w};V[k]=Q;return t}if(!L)throw Error("No Promise implementation available");var p,q,n;n=
requirejs||require;var M=Object.prototype.hasOwnProperty,V={},E=[],va=/^\.\//,oa=/^\/|\:|\?|\.js$/,ta=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,ua=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,I=/\.js$/,Z=Array.prototype.slice;"function"!==typeof requirejs&&(requirejs=p=Y("_"),"function"!==typeof require&&(require=p),p.exec=function(f){return eval(f)},p.contexts=V,define=function(){E.push(Z.call(arguments,0))},define.amd={jQuery:!0},n&&p.config(n),p.isBrowser&&!V._.config.skipDataMain&&(q=(q=
document.querySelectorAll("script[data-main]")[0])&&q.getAttribute("data-main")))&&(q=q.replace(I,""),n&&n.baseUrl||-1!==q.indexOf("!")||(n=q.split("/"),q=n.pop(),n=n.length?n.join("/")+"/":"./",p.config({baseUrl:n})),p([q]))})(this,"undefined"!==typeof Promise?Promise:void 0);