// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer({
    'is': 'cs-icon',
    properties: {
      icon: String,
      flipX: false,
      flipY: false,
      mono: false,
      rotate: 0,
      spin: false,
      spinStep: false,
      multiple_icons: {
        computed: '_multiple_icons(icon)',
        type: Boolean
      }
    },
    _multiple_icons: function(icon) {
      return icon.split(' ').length > 1;
    },
    icon_class: function(icon, flipX, flipY, mono, rotate, spin, spinStep) {
      var icon_class, icons, icons_classes, index, multiple_icons;
      icons = icon.split(' ');
      multiple_icons = icons.length > 1;
      icons_classes = (function() {
        var i, len, results;
        results = [];
        for (index = i = 0, len = icons.length; i < len; index = ++i) {
          icon = icons[index];
          icon_class = ['fa fa-' + icon];
          if (flipX) {
            icon_class.push('fa-flip-horizontal');
          }
          if (flipY) {
            icon_class.push('fa-flip-vertical');
          }
          if (mono) {
            icon_class.push('fa-fw');
          }
          if (rotate) {
            icon_class.push('fa-rotate-' + rotate);
          }
          if (spin) {
            icon_class.push('fa-spin');
          }
          if (spinStep) {
            icon_class.push('fa-pulse');
          }
          if (multiple_icons) {
            icon_class.push(index ? 'fa-stack-1x fa-inverse' : 'fa-stack-2x');
          }
          results.push(icon_class.join(' '));
        }
        return results;
      })();
      if (multiple_icons) {
        return icons_classes;
      } else {
        return icons_classes[0];
      }
    }
  });

}).call(this);
