// Generated by CoffeeScript 1.4.0

/**
 * @package       Shop
 * @order_status  modules
 * @author        Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright     Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license       MIT License, see license.txt
*/


(function() {

  (function(L) {
    return Polymer({
      publish: {
        description: '',
        address: '',
        amount: 0,
        label: ''
      },
      ready: function() {
        var _this = this;
        return $(function() {
          _this.description = JSON.parse(_this.description);
          _this.text = L.blockchain_payment_scan_or_transfer(_this.amount, _this.address);
          return $(_this.$.qr).qrcode('bitcoin:' + _this.address + '?amount=' + _this.amount + '&label=' + _this.label);
        });
      }
    });
  })(cs.Language);

}).call(this);
