// Generated by LiveScript 1.4.0
/**
 * @package    CleverStyle CMS
 * @subpackage System module
 * @category   modules
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2015, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */
(function(){
  var L;
  L = cs.Language;
  Polymer({
    'is': 'cs-system-admin-components-databases-list',
    behaviors: [cs.Polymer.behaviors.Language],
    ready: function(){
      this.reload();
    },
    reload: function(){
      var this$ = this;
      $.getJSON('api/System/admin/databases', function(databases){
        this$.set('databases', databases);
      });
    },
    _test_connection: function(e){
      var $modal;
      $modal = $(cs.ui.simple_modal("<div>\n	<h3 class=\"cs-text-center\">" + L.test_connection + "</h3>\n	<progress is=\"cs-progress\" infinite></progress>\n</div>"));
      $.ajax({
        url: 'api/System/admin/databases',
        data: e.model.database,
        type: 'test',
        success: function(result){
          $modal.find('progress').replaceWith("<p class=\"cs-text-center cs-block-success cs-text-success\" style=text-transform:capitalize;\">" + L.success + "</p>");
        },
        error: function(){
          $modal.find('progress').replaceWith("<p class=\"cs-text-center cs-block-error cs-text-error\" style=text-transform:capitalize;\">" + L.failed + "</p>");
        }
      });
    },
    _add: function(e){
      var database, this$ = this;
      database = e.model && e.model.database;
      $(cs.ui.simple_modal("<h3>" + L.addition_of_db + "</h3>\n<cs-system-admin-components-databases-form add database-index=\"" + (database && database.index) + "\"/>")).on('close', function(){
        this$.reload();
      });
    },
    _edit: function(e){
      var database, mirror, name, master_db_name, this$ = this;
      database = e.model.database;
      mirror = e.model.mirror;
      name = database.mirror
        ? (master_db_name = function(){
          var db;
          for (db in this$.databases) {
            if (db.index == database.index) {
              return db.name;
            }
          }
        }(), L.mirror + ' ' + (database.index
          ? L.db + ' ' + master_db_name
          : L.core_db))
        : L.db;
      name += " " + database.name + " " + database.host + "/" + database.type + ")";
      $(cs.ui.simple_modal("<h3>" + L.editing_the_database(name) + "</h3>\n<cs-system-admin-components-databases-form database-index=\"" + database.index + "\" mirror-index=\"" + (mirror && mirror.index) + "\"/>")).on('close', function(){
        this$.reload();
      });
    }
  });
}).call(this);
