// Generated by CoffeeScript 1.9.3

/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  var L;

  L = cs.Language;

  Polymer({
    'is': 'cs-blogs-post',
    'extends': 'article',
    behaviors: [cs.Polymer.behaviors.Language],
    properties: {
      can_edit: false,
      can_delete: false,
      comments_enabled: false
    },
    ready: function() {
      this.jsonld = JSON.parse(this.querySelector('script').innerHTML);
      this.$.content.innerHTML = this.jsonld.content;
      return $(this.shadowRoot).cs().tooltips_inside();
    },
    sections_path: function(index) {
      return this.jsonld.sections_paths[index];
    },
    tags_path: function(index) {
      return this.jsonld.tags_paths[index];
    }
  });

}).call(this);
