// Generated by LiveScript 1.4.0
/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2011-2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  $(function(){
    var title, content;
    if (cs.module !== 'Blogs') {
      return;
    }
    title = $('.cs-blogs-new-post-title');
    if (title.length) {
      window.onbeforeunload = function(){
        return true;
      };
    }
    content = $('.cs-blogs-new-post-content');
    $('.cs-blogs-post-preview').mousedown(function(){
      var data;
      data = {
        id: $(this).data('id'),
        title: title.val() || title.text(),
        sections: $('.cs-blogs-new-post-sections').val() || 0,
        content: content.val() || content.html(),
        tags: $('.cs-blogs-new-post-tags').val()
      };
      $.ajax({
        url: 'api/Blogs/posts',
        cache: false,
        data: data,
        type: 'preview',
        success: function(result){
          var preview;
          preview = $('.cs-blogs-post-preview-content');
          preview.html(result);
          $('html, body').stop().animate({
            scrollTop: preview.offset().top
          }, 500);
        }
      });
    });
    return $('.cs-blogs-post-form').parents('form').submit(function(){
      var form;
      window.onbeforeunload = null;
      form = $(this);
      if (!title.is('input')) {
        form.append($('<input name="title" hidden/>').val(title.text()));
      }
      if (!content.is('textarea')) {
        form.append($('<textarea name="content" hidden/>').val(content.html()));
      }
    });
  });
}).call(this);
