// Generated by CoffeeScript 1.9.3

/**
 * @package		HybridAuth
 * @category	modules
 * @author		HybridAuth authors
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com> (integration with CleverStyle CMS)
 * @copyright	HybridAuth authors
 * @license		MIT License, see license.txt
 */

(function() {
  $(function() {
    var dropdown, login_field, timeout;
    dropdown = document.querySelector('.cs-hybrid-auth-providers-list');
    if (dropdown) {
      login_field = $('.cs-header-sign-in-email');
      timeout = null;
      login_field.focus(function() {
        dropdown.target = this;
        return timeout = setTimeout((function() {
          return dropdown.open();
        }), 1000);
      });
      login_field.blur(function() {
        clearTimeout(timeout);
        return dropdown.open();
      });
    }
  });

}).call(this);
