// Generated by CoffeeScript 1.9.3

/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015-2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  var L;

  L = cs.Language;

  Polymer({
    'is': 'cs-blogs-head-actions',
    behaviors: [cs.Polymer.behaviors.Language],
    properties: {
      admin: false,
      can_write_post: false
    }
  });

}).call(this);
