// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer({
    'is': 'cs-label-switcher',
    'extends': 'label',
    behaviors: [Polymer.cs.behaviors.label, Polymer.cs.behaviors["this"]]
  });

}).call(this);
