// Generated by CoffeeScript 1.9.3

/**
 * @package   Picturefill
 * @category  plugins
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License
 */

(function() {
  Polymer({
    'is': 'cs-picturefill-img',
    'extends': 'img',
    ready: function() {
      picturefill({
        elements: [this]
      });
    }
  });

  Polymer({
    'is': 'cs-picturefill-picture',
    'extends': 'picture',
    ready: function() {
      picturefill({
        elements: [this.querySelector('img')]
      });
    }
  });

}).call(this);
