// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  var body;

  body = document.body;

  Polymer({
    'is': 'cs-section-modal',
    'extends': 'section',
    behaviors: [Polymer.cs.behaviors["this"]],
    properties: {
      content: {
        observer: '_content_changed',
        type: String
      },
      opened: {
        observer: '_opened_changed',
        reflectToAttribute: true,
        type: Boolean
      },
      transparent: {
        reflectToAttribute: true,
        type: Boolean
      }
    },
    created: function() {
      return this.style.display = 'none';
    },
    attached: function() {
      body.parentNode.appendChild(this);
      return setTimeout(((function(_this) {
        return function() {
          return _this.style.display = '';
        };
      })(this)), 100);
    },
    _content_changed: function() {
      return this.innerHTML = this.content;
    },
    _opened_changed: function() {
      body.modalOpened = body.modalOpened || 0;
      if (this.opened) {
        this.fire('open');
        document.body.setAttribute('modal-opened', '');
        return ++body.modalOpened;
      } else {
        this.fire('close');
        --body.modalOpened;
        if (!body.modalOpened) {
          return document.body.removeAttribute('modal-opened');
        }
      }
    },
    open: function() {
      this.opened = true;
      return this;
    },
    close: function() {
      this.opened = false;
      return this;
    }
  });

}).call(this);
