// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  var body;

  body = document.body;

  Polymer({
    'is': 'cs-section-modal',
    'extends': 'section',
    behaviors: [Polymer.cs.behaviors["this"]],
    properties: {
      content: String,
      opened: {
        observer: '_opened_changed',
        reflectToAttribute: true,
        type: Boolean
      },
      transparent: {
        reflectToAttribute: true,
        type: Boolean
      }
    },
    created: function() {
      this.style.display = 'none';
      return this._esc_handler = (function(_this) {
        return function(e) {
          if (e.keyCode === 27) {
            return _this.close();
          }
        };
      })(this);
    },
    attached: function() {
      document.addEventListener('keydown', this._esc_handler);
      body.parentNode.appendChild(this);
      return setTimeout(((function(_this) {
        return function() {
          return _this.style.display = '';
        };
      })(this)), 100);
    },
    detached: function() {
      return document.removeEventListener('keydown', this._esc_handler);
    },
    _opened_changed: function() {
      body.modalOpened = body.modalOpened || 0;
      if (this.opened) {
        if (this.content) {
          this.innerHTML = this.content;
          this.content = null;
        }
        ++body.modalOpened;
        this.fire('open');
        return document.body.setAttribute('modal-opened', '');
      } else {
        --body.modalOpened;
        this.fire('close');
        if (!body.modalOpened) {
          return document.body.removeAttribute('modal-opened');
        }
      }
    },
    open: function() {
      if (!this.opened) {
        this.opened = true;
      }
      return this;
    },
    close: function() {
      if (this.opened) {
        this.opened = false;
      }
      return this;
    }
  });

}).call(this);
