// Generated by CoffeeScript 1.9.3

/**
 * @package    CleverStyle CMS
 * @subpackage System module
 * @category   modules
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2011-2015, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */

(function() {
  var L;

  L = cs.Language;


  /**
   * Cache cleaning
   *
   * @param 			element
   * @param {string}	action
   */

  cs.admin_cache = function(element, action, partial_path) {
    $(element).html("<progress is=\"cs-progress\" infinite></progress>");
    $.ajax({
      url: action,
      data: {
        partial_path: partial_path
      },
      type: 'delete',
      success: function(result) {
        return $(element).html(result ? "<p class=\"cs-block-success cs-text-success\">" + L.done + "</p>" : "<p class=\"cs-block-errorcs-text-error\">" + L.error + "</p>");
      }
    });
  };

  cs.test_email_sending = function() {
    var email;
    email = prompt(L.email);
    if (email) {
      return $.ajax({
        url: 'api/System/admin/email_sending_test',
        data: {
          email: email
        },
        type: 'get',
        success: function() {
          return alert(L.done);
        },
        error: function() {
          return alert(L.test_email_sending_failed);
        }
      });
    }
  };

}).call(this);
