// Generated by CoffeeScript 1.9.3

/**
 * @package    CleverStyle CMS
 * @category   modules
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright  Copyright (c) 2011-2015, Nazar Mokrynskyi
 * @license    MIT License, see license.txt
 */

(function() {
  $(function() {
    return requestAnimationFrame(function() {
      if (!cs.in_admin) {
        return;
      }
      $('.cs-reload-button').click(function() {
        return location.reload();
      });
      $('#change_active_languages').change(function() {
        return $(this).find("option[value='" + $('#change_language').val() + "']").prop('selected', true);
      });
      $('#cs-users-groups-list, #cs-users-groups-list-selected').sortable({
        connectWith: '#cs-users-groups-list, #cs-users-groups-list-selected',
        items: 'li:not(:first)',
        placeholder: '<li class="cs-block-primary">'
      }).on('sortupdate', function() {
        var selected;
        $('#cs-users-groups-list').find('.cs-block-success').removeClass('cs-block-success cs-text-success').addClass('cs-block-warning cs-text-warning');
        selected = $('#cs-users-groups-list-selected');
        selected.find('.cs-block-warning').removeClass('cs-block-warning cs-text-warning').addClass('cs-block-success cs-text-success');
        return $('#cs-user-groups').val(JSON.stringify(selected.children('li:not(:first)').map(function() {
          return this.dataset.id;
        }).get()));
      });
    });
  });

}).call(this);
