// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer.cs.behaviors.button = {
    properties: {
      active: {
        notify: true,
        reflectToAttribute: true,
        type: Boolean
      },
      empty: {
        reflectToAttribute: true,
        type: Boolean
      },
      icon: {
        reflectToAttribute: true,
        type: String
      },
      primary: {
        reflectToAttribute: true,
        type: Boolean
      }
    },
    ready: function() {
      if (!this.childNodes.length) {
        return this.empty = true;
      }
    }
  };

}).call(this);
