// Generated by CoffeeScript 1.9.3

/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  Polymer.cs.behaviors["this"] = {
    properties: {
      'this': {
        notify: true,
        readOnly: true,
        type: Object
      }
    },
    ready: function() {
      return this._setThis(this);
    }
  };

}).call(this);
