// Generated by LiveScript 1.4.0
/**
 * @package   Static pages
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2016, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  Polymer({
    'is': 'cs-static-pages-admin-categories-list',
    behaviors: [cs.Polymer.behaviors.Language('static_pages_')],
    properties: {
      categories: Array
    },
    ready: function(){
      this._reload_categories();
    },
    _reload_categories: function(){
      var this$ = this;
      cs.api('get api/Static_pages/admin/categories').then(function(categories){
        this$.set('categories', categories);
      });
    }
  });
}).call(this);
