ALTER TABLE `[prefix]groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]groups_permissions` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]sign_ins` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]sessions` DROP PRIMARY KEY, ADD PRIMARY KEY (`id`(32), `expire`, `user_agent`(191), `remote_addr`(32), `ip`(32));
ALTER TABLE `[prefix]sessions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]users_data` DROP PRIMARY KEY, ADD PRIMARY KEY (`id`, `item`(191));
ALTER TABLE `[prefix]users_data` DROP INDEX `item`, ADD INDEX `item` (`item`(191));
ALTER TABLE `[prefix]users_data` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]users_groups` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `[prefix]users_permissions` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
REPAIR TABLE `[prefix]groups`;
OPTIMIZE TABLE `[prefix]groups`;
REPAIR TABLE `[prefix]groups_permissions`;
OPTIMIZE TABLE `[prefix]groups_permissions`;
REPAIR TABLE `[prefix]sign_ins`;
OPTIMIZE TABLE `[prefix]sign_ins`;
REPAIR TABLE `[prefix]permissions`;
OPTIMIZE TABLE `[prefix]permissions`;
REPAIR TABLE `[prefix]sessions`;
OPTIMIZE TABLE `[prefix]sessions`;
REPAIR TABLE `[prefix]users`;
OPTIMIZE TABLE `[prefix]users`;
REPAIR TABLE `[prefix]users_data`;
OPTIMIZE TABLE `[prefix]users_data`;
REPAIR TABLE `[prefix]users_groups`;
OPTIMIZE TABLE `[prefix]users_groups`;
REPAIR TABLE `[prefix]users_permissions`;
OPTIMIZE TABLE `[prefix]users_permissions`;
