// Generated by LiveScript 1.5.0
/**
 * @package    CleverStyle Framework
 * @subpackage DarkEnergy theme
 * @author     Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license    0BSD
 */
(function(){
  cs.ui.ready.then(function(){
    document.querySelector('.cs-mobile-menu').addEventListener('click', function(){
      if (this.hasAttribute('show')) {
        this.removeAttribute('show');
      } else {
        this.setAttribute('show', '');
      }
    });
  });
}).call(this);
