// Generated by CoffeeScript 1.9.3

/**
 * @package   Shop
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */

(function() {
  $(function() {
    var L, make_modal, set_attribute_types;
    L = cs.Language;
    set_attribute_types = [1, 2, 6, 9];
    make_modal = function(types, title, action) {
      var index, type;
      types = (function() {
        var results;
        results = [];
        for (index in types) {
          type = types[index];
          results.push("<option value=\"" + index + "\">" + type + "</option>");
        }
        return results;
      })();
      types = types.join('');
      return cs.ui.simple_modal("<form>\n	<h3 class=\"cs-text-center\">" + title + "</h3>\n	<p>\n		" + L.shop_attribute_type + ": <select is=\"cs-select\" name=\"type\" required>" + types + "</select>\n	</p>\n	<p>\n		" + L.shop_possible_values + ": <textarea is=\"cs-textarea\" autosize name=\"value\"></textarea>\n	</p>\n	<p>\n		" + L.shop_title + ": <input is=\"cs-input-title\" name=\"title\" required>\n	</p>\n	<p>\n		" + L.shop_title_internal + ": <input is=\"cs-input-title\" name=\"title_internal\" required>\n	</p>\n	<p>\n		<button is=\"cs-button\" type=\"submit\">" + action + "</button>\n	</p>\n</form>");
    };
    return $('html').on('mousedown', '.cs-shop-attribute-add', function() {
      return $.getJSON('api/Shop/admin/attributes/types', function(types) {
        var modal;
        modal = make_modal(types, L.shop_attribute_addition, L.shop_add);
        return modal.on('submit', 'form', function() {
          var type, value;
          type = modal.find('[name=type]').val();
          value = set_attribute_types.indexOf(parseInt(type)) !== -1 ? modal.find('[name=value]').val().split('\n') : '';
          $.ajax({
            url: 'api/Shop/admin/attributes',
            type: 'post',
            data: {
              type: type,
              title: modal.find('[name=title]').val(),
              title_internal: modal.find('[name=title_internal]').val(),
              value: value
            },
            success: function() {
              alert(L.shop_added_successfully);
              return location.reload();
            }
          });
          return false;
        }).on('change', '[name=type]', function() {
          var type, value_container;
          value_container = $(this).parent().next();
          type = $(this).val();
          if (set_attribute_types.indexOf(parseInt(type)) !== -1) {
            return value_container.show();
          } else {
            return value_container.hide();
          }
        });
      });
    }).on('mousedown', '.cs-shop-attribute-edit', function() {
      var id;
      id = $(this).data('id');
      return $.when($.getJSON('api/Shop/admin/attributes/types'), $.getJSON("api/Shop/admin/attributes/" + id)).done(function(types, attribute) {
        var modal;
        modal = make_modal(types[0], L.shop_attribute_edition, L.shop_edit);
        modal.on('submit', 'form', function() {
          var type, value;
          type = modal.find('[name=type]').val();
          value = set_attribute_types.indexOf(parseInt(type)) !== -1 ? modal.find('[name=value]').val().split('\n') : '';
          $.ajax({
            url: "api/Shop/admin/attributes/" + id,
            type: 'put',
            data: {
              type: type,
              title: modal.find('[name=title]').val(),
              title_internal: modal.find('[name=title_internal]').val(),
              value: value
            },
            success: function() {
              alert(L.shop_edited_successfully);
              return location.reload();
            }
          });
          return false;
        }).on('change', '[name=type]', function() {
          var type, value_container;
          value_container = $(this).parent().next();
          type = $(this).val();
          if (set_attribute_types.indexOf(parseInt(type)) !== -1) {
            return value_container.show();
          } else {
            return value_container.hide();
          }
        });
        attribute = attribute[0];
        modal.find('[name=type]').val(attribute.type).change();
        modal.find('[name=value]').val(attribute.value ? attribute.value.join('\n') : '');
        modal.find('[name=title]').val(attribute.title);
        return modal.find('[name=title_internal]').val(attribute.title_internal);
      });
    }).on('mousedown', '.cs-shop-attribute-delete', function() {
      var id;
      id = $(this).data('id');
      if (confirm(L.shop_sure_want_to_delete)) {
        return $.ajax({
          url: "api/Shop/admin/attributes/" + id,
          type: 'delete',
          success: function() {
            alert(L.shop_deleted_successfully);
            return location.reload();
          }
        });
      }
    });
  });

}).call(this);
